[[redirects]]
  from = "/api/groq/*"
  to = "https://api.groq.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/openrouter/*"
  to = "https://openrouter.ai/:splat"
  status = 200
  force = true
